### PR TITLE
add nov22-23 numpy sprint

### PR DESCRIPTION
**Pull request by mattip**

### CODE REVIEW

**Comment by mattip** [comment]
It seems after merge-to-master one runs the push_dir_to_repo.py script?

**Comment by NelleV** [comment]
If I recall correctly, yes. We should really change this to use travis to build everything.

**Comment by mattip** [comment]
ok. Will wait a few days for updates/corrections before merging and pushing, thanks

**Comment by stefanv** [comment]
I didn't set up Travis, because it seemed easy enough to just build it and push.  But, if someone else volunteers, sure :)

**Comment by NelleV** [comment]
It's actually super easy to set up through travis these days. I'll do it if
I feel like procrastinating from preparing my course :)

**Comment by mattip** [comment]
@stefanv should I merge and publish this?

**Comment by stefanv** [comment]
Merged and deployed.

**Pull request merged**
